version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: nuxt_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nuxt_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
